-- Portable DDL: runs unchanged on H2 (MODE=PostgreSQL) and PostgreSQL.
-- The unique constraints are the authoritative concurrency guarantees; see docs/adr/0004.

CREATE TABLE url_mapping (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code          VARCHAR(6)               NOT NULL,
    destination_url     VARCHAR(2048)            NOT NULL,
    normalized_url      VARCHAR(2048)            NOT NULL,
    normalized_url_hash VARCHAR(64)              NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_url_mapping_short_code UNIQUE (short_code),
    -- Unique on the SHA-256 of the normalized URL rather than the URL itself:
    -- a unique btree index on a 2048-char column can exceed PostgreSQL's index row size limit.
    CONSTRAINT uk_url_mapping_normalized_url_hash UNIQUE (normalized_url_hash)
);

CREATE TABLE click_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_mapping_id BIGINT                   NOT NULL,
    clicked_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_click_event_url_mapping FOREIGN KEY (url_mapping_id) REFERENCES url_mapping (id)
);

CREATE INDEX ix_click_event_mapping_clicked_at ON click_event (url_mapping_id, clicked_at);
